-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    country character varying(255) COLLATE pg_catalog."default",
    ctarea character varying(255) COLLATE pg_catalog."default",
    field1 character varying(255) COLLATE pg_catalog."default",
    field2 character varying(255) COLLATE pg_catalog."default",
    pinno character varying(255) COLLATE pg_catalog."default",
    state character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT address_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attendance
(
    id bigint NOT NULL,
    attendance_status timestamp(6) without time zone NOT NULL,
    description character varying(500) COLLATE pg_catalog."default",
    is_attended boolean NOT NULL,
    is_customer_agreed boolean NOT NULL,
    is_resolved boolean NOT NULL,
    taskstatus character varying(255) COLLATE pg_catalog."default",
    customerid bigint NOT NULL,
    serviceproviderid bigint NOT NULL,
    CONSTRAINT attendance_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.booking_transaction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount double precision NOT NULL,
    createdon timestamp(6) without time zone NOT NULL,
    transactionid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    engagement_id bigint NOT NULL,
    CONSTRAINT booking_transaction_pkey PRIMARY KEY (id),
    CONSTRAINT ukiabppyhkomirmgi6r02epx8on UNIQUE (transactionid),
    CONSTRAINT ukq90yixy5ourcq2ntcple59et UNIQUE (engagement_id)
);

CREATE TABLE IF NOT EXISTS public.coupons
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    counter bigint,
    country_code integer,
    coupon_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    created_by character varying(30) COLLATE pg_catalog."default",
    created_on timestamp(6) without time zone,
    currency_code character varying(3) COLLATE pg_catalog."default",
    description character varying(200) COLLATE pg_catalog."default",
    discount_percent integer,
    expiry_date date,
    fixed_disc_amt integer,
    is_valid integer,
    max_disc_amount integer,
    modified_by character varying(30) COLLATE pg_catalog."default",
    modified_on timestamp(6) without time zone,
    start_date date,
    status character varying(30) COLLATE pg_catalog."default",
    to_be_availed_by integer,
    total_availed_amt bigint,
    validity_period integer,
    CONSTRAINT coupons_pkey PRIMARY KEY (id),
    CONSTRAINT ukctujg6iiegcw3kgrm2at8p871 UNIQUE (coupon_code)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    customerid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    kyc character varying(255) COLLATE pg_catalog."default",
    alternateno bigint,
    buildingname character varying(255) COLLATE pg_catalog."default",
    currentlocation character varying(255) COLLATE pg_catalog."default",
    emailid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    enrolleddate timestamp(6) without time zone,
    firstname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    idno character varying(255) COLLATE pg_catalog."default",
    isactive boolean NOT NULL,
    languageknown character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    locality character varying(255) COLLATE pg_catalog."default",
    middlename character varying(255) COLLATE pg_catalog."default",
    mobileno bigint,
    pincode integer,
    profilepic character varying(255) COLLATE pg_catalog."default",
    rating double precision NOT NULL,
    speciality character varying(255) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (customerid),
    CONSTRAINT ukd6doygr7mh7jilpaxc5iw8iac UNIQUE (emailid),
    CONSTRAINT uksyres1de33wdw2ax48fqv2t54 UNIQUE (mobileno)
);

CREATE TABLE IF NOT EXISTS public.customer_holidays
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    applyholidaydate timestamp(6) without time zone NOT NULL,
    enddate date NOT NULL,
    isactive boolean NOT NULL,
    servicetype character varying(100) COLLATE pg_catalog."default",
    startdate date NOT NULL,
    customer_id bigint,
    engagement_id bigint NOT NULL,
    CONSTRAINT customer_holidays_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_leaves
(
    leave_id bigserial NOT NULL,
    customerid bigint,
    engagement_id bigint,
    leave_type character varying(50) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'PENDING'::character varying,
    reason text COLLATE pg_catalog."default",
    leave_start_date date,
    leave_end_date date,
    start_date date,
    end_date date,
    total_days integer,
    refund_amount numeric(12, 2),
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT customer_leaves_pkey PRIMARY KEY (leave_id)
);

CREATE TABLE IF NOT EXISTS public.customer_payments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    baseamount double precision NOT NULL,
    coupon_discount_amount double precision,
    discountamount double precision NOT NULL,
    enddate_p date NOT NULL,
    finalamount double precision NOT NULL,
    generatedon timestamp(6) without time zone NOT NULL,
    paymentmode character varying(255) COLLATE pg_catalog."default" NOT NULL,
    paymentmonth date NOT NULL,
    paymenton date NOT NULL,
    startdate_p date NOT NULL,
    transactionid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    coupon_id bigint,
    customer_id bigint,
    engagement_id bigint NOT NULL,
    CONSTRAINT customer_payments_pkey PRIMARY KEY (id),
    CONSTRAINT ukndsk4w7j76yx1o68b3r8bmw37 UNIQUE (transactionid)
);

CREATE TABLE IF NOT EXISTS public.customer_used_coupons
(
    availed_amount integer,
    availed_on timestamp(6) without time zone,
    coupon_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    engagement_id bigint NOT NULL,
    CONSTRAINT customer_used_coupons_pkey PRIMARY KEY (coupon_id, customer_id)
);

CREATE TABLE IF NOT EXISTS public.customer_wallets
(
    wallet_id bigint NOT NULL DEFAULT nextval('wallets_wallet_id_seq'::regclass),
    customerid bigint,
    balance numeric(10, 2) DEFAULT 0,
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT wallets_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT wallets_customerid_key UNIQUE (customerid)
);

CREATE TABLE IF NOT EXISTS public.customerconcern
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    createdon timestamp(6) without time zone NOT NULL,
    customerid bigint,
    feedback character varying(500) COLLATE pg_catalog."default",
    isresolved character varying(255) COLLATE pg_catalog."default" NOT NULL,
    modifiedon timestamp(6) without time zone,
    resolutionrequired character varying(255) COLLATE pg_catalog."default" NOT NULL,
    resolvedby bigint,
    resolvedon timestamp(6) without time zone,
    CONSTRAINT customerconcern_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customerfeedback
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(500) COLLATE pg_catalog."default",
    commentedon timestamp(6) without time zone NOT NULL,
    rating integer NOT NULL,
    customerid bigint NOT NULL,
    serviceproviderid bigint NOT NULL,
    customername character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT customerfeedback_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customerrequest
(
    requestid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    agerange character varying(255) COLLATE pg_catalog."default",
    amount double precision,
    apartment_name character varying(255) COLLATE pg_catalog."default",
    area character varying(255) COLLATE pg_catalog."default",
    assigneddate timestamp(6) without time zone NOT NULL,
    cookinghabit character varying(255) COLLATE pg_catalog."default",
    createddate timestamp(6) without time zone NOT NULL,
    customerid bigint,
    days character varying(255) COLLATE pg_catalog."default",
    dietryhabit character varying(255) COLLATE pg_catalog."default",
    enddate timestamp(6) without time zone,
    gender character varying(255) COLLATE pg_catalog."default",
    housekeepingrole character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ispotential character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isresolved character varying(255) COLLATE pg_catalog."default" NOT NULL,
    languageknown character varying(255) COLLATE pg_catalog."default",
    locality character varying(255) COLLATE pg_catalog."default",
    modifiedby bigint,
    modifieddate timestamp(6) without time zone,
    noofresources character varying(255) COLLATE pg_catalog."default",
    pincode integer NOT NULL,
    serviceproviderid bigint,
    startdate timestamp(6) without time zone,
    status character varying(255) COLLATE pg_catalog."default",
    supervisorid bigint,
    timeslotlist character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT customerrequest_pkey PRIMARY KEY (requestid)
);

CREATE TABLE IF NOT EXISTS public.customerrequestcomment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default" NOT NULL,
    commentedby character varying(255) COLLATE pg_catalog."default" NOT NULL,
    commentedon timestamp(6) without time zone NOT NULL,
    requestid bigint NOT NULL,
    CONSTRAINT customerrequestcomment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.engagement_modifications
(
    modification_id bigserial NOT NULL,
    engagement_id bigint,
    modification_type character varying(50) COLLATE pg_catalog."default",
    old_start_date date,
    old_end_date date,
    new_start_date date,
    new_end_date date,
    created_at timestamp without time zone DEFAULT now(),
    modified_fields jsonb,
    modified_by_id bigint,
    modified_by_role character varying(50) COLLATE pg_catalog."default",
    modified_at timestamp without time zone DEFAULT now(),
    modified_by bigint,
    modified_type character varying(50) COLLATE pg_catalog."default",
    modified_data jsonb,
    CONSTRAINT engagement_modifications_pkey PRIMARY KEY (modification_id)
);

CREATE TABLE IF NOT EXISTS public.engagements
(
    engagement_id bigserial NOT NULL,
    customerid bigint,
    serviceproviderid bigint,
    responsibilities jsonb DEFAULT '[]'::jsonb,
    booking_type character varying(50) COLLATE pg_catalog."default",
    service_type character varying(50) COLLATE pg_catalog."default",
    base_amount numeric(10, 2) DEFAULT 0,
    start_date date,
    end_date date,
    task_status character varying(50) COLLATE pg_catalog."default" DEFAULT 'NOT_STARTED'::character varying,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    assignment_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'UNASSIGNED'::character varying,
    vacation_start_date date,
    vacation_end_date date,
    leave_days integer DEFAULT 0,
    vacation_priority_provider_id bigint,
    start_epoch bigint,
    end_epoch bigint,
    provider_gender_preference character varying(50) COLLATE pg_catalog."default" DEFAULT 'No Preference',
    CONSTRAINT engagements_pkey PRIMARY KEY (engagement_id)
);

CREATE TABLE IF NOT EXISTS public.kyc
(
    kyc_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_kyc_validated boolean NOT NULL,
    is_kyc_validated_by bigint,
    is_kyc_validated_on timestamp(6) without time zone,
    kyc_doc oid,
    kyc_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    kyc_type_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    service_provider_id bigint NOT NULL,
    stage character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT kyc_pkey PRIMARY KEY (kyc_id),
    CONSTRAINT uk1ubetgj4wxrmjyk27hlh4xxyl UNIQUE (kyc_type_id)
);

CREATE TABLE IF NOT EXISTS public.kyc_comments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default",
    commented_by character varying(100) COLLATE pg_catalog."default",
    commented_on timestamp(6) without time zone NOT NULL,
    serviceproviderid bigint NOT NULL,
    kyc_id bigint NOT NULL,
    CONSTRAINT kyc_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.leave_balance
(
    balance_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    leave_balance integer,
    leave_taken integer NOT NULL,
    leavetype character varying(255) COLLATE pg_catalog."default",
    total_leaves integer NOT NULL,
    serviceproviderid bigint NOT NULL,
    CONSTRAINT leave_balance_pkey PRIMARY KEY (balance_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id bigserial NOT NULL,
    engagement_id bigint,
    base_amount numeric(10, 2) NOT NULL,
    platform_fee numeric(10, 2) NOT NULL,
    gst numeric(10, 2) NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    payment_mode character varying(50) COLLATE pg_catalog."default",
    transaction_id character varying(255) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'PENDING'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    razorpay_order_id character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.payouts
(
    payout_id bigserial NOT NULL,
    serviceproviderid bigint,
    engagement_id bigint,
    gross_amount numeric(10, 2),
    provider_fee numeric(10, 2),
    tds_amount numeric(10, 2),
    net_amount numeric(10, 2),
    payout_mode character varying(50) COLLATE pg_catalog."default",
    transaction_id character varying(255) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'INITIATED'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT payouts_pkey PRIMARY KEY (payout_id)
);

CREATE TABLE IF NOT EXISTS public.provider_availability
(
    id bigserial NOT NULL,
    serviceproviderid bigint,
    engagement_id bigint,
    date date NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'BOOKED'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    slot_start_epoch bigint,
    slot_end_epoch bigint,
    CONSTRAINT provider_availability_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provider_leaves
(
    leave_id bigserial NOT NULL,
    serviceproviderid bigint,
    engagement_id bigint,
    start_date date,
    end_date date,
    reason text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'PENDING'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT provider_leaves_pkey PRIMARY KEY (leave_id)
);

CREATE TABLE IF NOT EXISTS public.provider_wallets
(
    wallet_id bigserial NOT NULL,
    serviceproviderid bigint,
    balance numeric(10, 2) DEFAULT 0,
    security_deposit_collected numeric(10, 2) DEFAULT 0,
    CONSTRAINT provider_wallets_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT provider_wallets_serviceproviderid_key UNIQUE (serviceproviderid)
);

CREATE TABLE IF NOT EXISTS public.provider_ledger
(
    ledger_id bigserial NOT NULL,
    serviceproviderid bigint NOT NULL,
    engagement_id bigint,
    amount numeric(12, 2) NOT NULL,
    direction character varying(10) COLLATE pg_catalog."default",
    reason character varying(50) COLLATE pg_catalog."default",
    reference_type character varying(50) COLLATE pg_catalog."default",
    reference_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT provider_ledger_pkey PRIMARY KEY (ledger_id)
);

CREATE TABLE IF NOT EXISTS public.service_provider_feedback
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    feedback character varying(255) COLLATE pg_catalog."default",
    rating double precision NOT NULL,
    customer_id bigint NOT NULL,
    service_provider_id bigint NOT NULL,
    CONSTRAINT service_provider_feedback_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service_provider_leave
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    appliedon date,
    approvedby integer,
    approvedon date,
    description character varying(255) COLLATE pg_catalog."default",
    from_date date NOT NULL,
    isapproved boolean,
    isbackuprequired boolean,
    iscustomerinformed boolean,
    leavetype character varying(255) COLLATE pg_catalog."default",
    no_of_days integer,
    to_date date NOT NULL,
    backup_by_id bigint,
    serviceproviderid bigint NOT NULL,
    CONSTRAINT service_provider_leave_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service_provider_payment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    upiid character varying(255) COLLATE pg_catalog."default",
    amount integer NOT NULL,
    currency character varying(255) COLLATE pg_catalog."default",
    enddate date NOT NULL,
    month integer,
    monthlyamount integer NOT NULL,
    noofdays double precision NOT NULL,
    paymentmode character varying(255) COLLATE pg_catalog."default" NOT NULL,
    paymenton date,
    settledon timestamp(6) without time zone,
    startdate date NOT NULL,
    transactionid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    year integer,
    customerid bigint NOT NULL,
    serviceproviderid bigint NOT NULL,
    CONSTRAINT service_provider_payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service_provider_request_comments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default" NOT NULL,
    commented_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    commented_on timestamp(6) without time zone NOT NULL,
    requestid bigint NOT NULL,
    CONSTRAINT service_provider_request_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service_provider_used_coupons
(
    availed_amount integer,
    availed_on timestamp(6) without time zone,
    coupon_id bigint NOT NULL,
    service_provider_id bigint NOT NULL,
    CONSTRAINT service_provider_used_coupons_pkey PRIMARY KEY (coupon_id, service_provider_id)
);

CREATE TABLE IF NOT EXISTS public.serviceprovider
(
    serviceproviderid bigint NOT NULL,
    dob date,
    kyc character varying(255) COLLATE pg_catalog."default",
    age integer,
    alternateno bigint,
    buildingname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cookingspeciality character varying(255) COLLATE pg_catalog."default",
    currentlocation character varying(255) COLLATE pg_catalog."default",
    diet character varying(255) COLLATE pg_catalog."default",
    emailid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    enrolleddate timestamp(6) without time zone,
    experience integer,
    firstname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    geohash4 character varying(255) COLLATE pg_catalog."default",
    geohash5 character varying(255) COLLATE pg_catalog."default",
    geohash6 character varying(255) COLLATE pg_catalog."default",
    geohash7 character varying(255) COLLATE pg_catalog."default",
    housekeepingrole character varying(255) COLLATE pg_catalog."default",
    idno character varying(255) COLLATE pg_catalog."default",
    info character varying(255) COLLATE pg_catalog."default",
    isactive boolean NOT NULL,
    languageknown character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    latitude double precision,
    locality character varying(255) COLLATE pg_catalog."default" NOT NULL,
    location character varying(255) COLLATE pg_catalog."default",
    longitude double precision,
    middlename character varying(255) COLLATE pg_catalog."default",
    mobileno bigint NOT NULL,
    nearbylocation character varying(255) COLLATE pg_catalog."default",
    pincode integer NOT NULL,
    profilepic character varying(255) COLLATE pg_catalog."default",
    rating double precision NOT NULL,
    speciality character varying(255) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default" NOT NULL,
    timeslot character varying(255) COLLATE pg_catalog."default",
    vendorid bigint,
    security_deposit_collected numeric DEFAULT 0,
    correspondence_apartment character varying(255) COLLATE pg_catalog."default",
    correspondence_city character varying(255) COLLATE pg_catalog."default",
    correspondence_country character varying(255) COLLATE pg_catalog."default",
    correspondence_pincode character varying(255) COLLATE pg_catalog."default",
    correspondence_state character varying(255) COLLATE pg_catalog."default",
    correspondence_street character varying(255) COLLATE pg_catalog."default",
    permanent_apartment character varying(255) COLLATE pg_catalog."default",
    permanent_city character varying(255) COLLATE pg_catalog."default",
    permanent_country character varying(255) COLLATE pg_catalog."default",
    permanent_pincode character varying(255) COLLATE pg_catalog."default",
    permanent_state character varying(255) COLLATE pg_catalog."default",
    permanent_street character varying(255) COLLATE pg_catalog."default",
    key_facts boolean,
    correspondence_address_id bigint,
    permanent_address_id bigint,
    CONSTRAINT serviceprovider_pkey PRIMARY KEY (serviceproviderid),
    CONSTRAINT uk1jnw9x79lpu3a7xipwo2mis6m UNIQUE (emailid),
    CONSTRAINT uk8c38m2dawmd5ks1m0v1mdvaqm UNIQUE (correspondence_address_id),
    CONSTRAINT ukedeoutrqlypkbdcef08w78bwn UNIQUE (mobileno),
    CONSTRAINT ukqt70pwr65bckmjmdftw66r40o UNIQUE (permanent_address_id)
);

CREATE TABLE IF NOT EXISTS public.serviceproviderrequest
(
    requestid bigint NOT NULL,
    age integer,
    createdon timestamp(6) without time zone NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    housekeepingrole character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ispotential character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isresolved character varying(255) COLLATE pg_catalog."default" NOT NULL,
    modifiedon timestamp(6) without time zone NOT NULL,
    resolvedby bigint,
    resolvedon timestamp(6) without time zone,
    serviceproviderid bigint,
    supervisorid bigint,
    timeslotlist character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT serviceproviderrequest_pkey PRIMARY KEY (requestid)
);

CREATE TABLE IF NOT EXISTS public.shortlisted_service_provider
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    serviceprovideridlist character varying(255) COLLATE pg_catalog."default",
    customerid bigint NOT NULL,
    CONSTRAINT shortlisted_service_provider_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_credentials
(
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    disable_till timestamp(6) without time zone,
    is_active boolean NOT NULL,
    is_temp_locked boolean NOT NULL,
    last_login timestamp(6) without time zone,
    no_of_tries integer NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(10) COLLATE pg_catalog."default",
    user_role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_credentials_pkey PRIMARY KEY (username),
    CONSTRAINT ukffrnqq2cgqiv3nqlw6vmw5sx0 UNIQUE (phone_number)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vendor
(
    vendorid bigint NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    companyname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    createddate timestamp(6) without time zone,
    emailid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isactive boolean NOT NULL,
    phoneno bigint NOT NULL,
    registrationid character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT vendor_pkey PRIMARY KEY (vendorid),
    CONSTRAINT ukai497u87sxgg9h3i37ylnllp9 UNIQUE (emailid),
    CONSTRAINT uks644wf0wmfwp3236ki8kxknfj UNIQUE (phoneno),
    CONSTRAINT uksua06yf2eer2f31e8k904rosj UNIQUE (registrationid)
);

CREATE TABLE IF NOT EXISTS public.provider_reviews (
  review_id BIGSERIAL PRIMARY KEY,

  customerid BIGINT NOT NULL,
  serviceproviderid BIGINT NOT NULL,
  engagement_id BIGINT NOT NULL UNIQUE,

  service_type VARCHAR(50) NOT NULL
    CHECK (service_type IN ('ON_DEMAND', 'SHORT_TERM', 'MONTHLY')),

  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review TEXT,

  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),

  CONSTRAINT fk_review_customer
    FOREIGN KEY (customerid)
    REFERENCES customer(customerid),

  CONSTRAINT fk_review_serviceprovider
    FOREIGN KEY (serviceproviderid)
    REFERENCES serviceprovider(serviceproviderid),

  CONSTRAINT fk_review_engagement
    FOREIGN KEY (engagement_id)
    REFERENCES engagements(engagement_id)
);

CREATE TABLE IF NOT EXISTS public.wallet_transaction
(
    transaction_id bigint NOT NULL DEFAULT nextval('wallet_transactions_transaction_id_seq'::regclass),
    customerid bigint,
    engagement_id bigint,
    transaction_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(12, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    balance_after numeric(12, 2),
    created_at timestamp without time zone DEFAULT now(),
    wallet_id bigint,
    reason text COLLATE pg_catalog."default",
    CONSTRAINT wallet_transactions_pkey PRIMARY KEY (transaction_id)
);



CREATE TABLE IF NOT EXISTS public.wallet_transactions
(
    transaction_id bigserial NOT NULL,
    customerid bigint,
    engagement_id bigint,
    transaction_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(12, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    balance_after numeric(12, 2),
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT wallet_transactions_pkey1 PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.wallets
(
    wallet_id bigserial NOT NULL,
    customerid bigint,
    balance numeric(10, 2) DEFAULT 0,
    CONSTRAINT wallets_pkey1 PRIMARY KEY (wallet_id),
    CONSTRAINT wallets_customerid_key1 UNIQUE (customerid)
);

ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT fke150vehlbirwe0cdw2icb8np4 FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT fklitkdnhf0h29tny0q5usvpevv FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking_transaction
    ADD CONSTRAINT booking_transaction_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukq90yixy5ourcq2ntcple59et
    ON public.booking_transaction(engagement_id);


ALTER TABLE IF EXISTS public.customer_holidays
    ADD CONSTRAINT customer_holidays_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_holidays
    ADD CONSTRAINT fkofahpk67fvlvwrssm4t7evjt FOREIGN KEY (customer_id)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_leaves
    ADD CONSTRAINT customer_leaves_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_leaves
    ADD CONSTRAINT customer_leaves_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_payments
    ADD CONSTRAINT fkh34yv8veqbjgardvcnqlkbv52 FOREIGN KEY (customer_id)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_payments
    ADD CONSTRAINT fkm97i2iuqhktsnicqlpdubttre FOREIGN KEY (coupon_id)
    REFERENCES public.coupons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_payments
    ADD CONSTRAINT customer_payments_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_used_coupons
    ADD CONSTRAINT fka8biu5lk7k8h263pl45s6v539 FOREIGN KEY (coupon_id)
    REFERENCES public.coupons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_used_coupons
    ADD CONSTRAINT customer_used_coupons_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_used_coupons
    ADD CONSTRAINT fkljiyjlufwiogt7h01w2eduggg FOREIGN KEY (customer_id)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_wallets
    ADD CONSTRAINT wallets_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS wallets_customerid_key
    ON public.customer_wallets(customerid);


ALTER TABLE IF EXISTS public.customerfeedback
    ADD CONSTRAINT fkbyf1ltiptm0lhl4d1rglkxevv FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customerfeedback
    ADD CONSTRAINT fkmefrx4uwct97k6irm4cks4sok FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customerrequestcomment
    ADD CONSTRAINT fksip64pjkqkkl03x9994uhhreu FOREIGN KEY (requestid)
    REFERENCES public.customerrequest (requestid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.engagement_modifications
    ADD CONSTRAINT engagement_modifications_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.engagements
    ADD CONSTRAINT engagements_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.engagements
    ADD CONSTRAINT engagements_serviceproviderid_fkey FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.kyc_comments
    ADD CONSTRAINT fk74qx4i2e1x3vf4nv68y0djbqk FOREIGN KEY (kyc_id)
    REFERENCES public.kyc (kyc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.leave_balance
    ADD CONSTRAINT fkfa2ha5yjdwfr61y3w9dwbpugk FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payouts
    ADD CONSTRAINT payouts_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payouts
    ADD CONSTRAINT payouts_serviceproviderid_fkey FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provider_availability
    ADD CONSTRAINT provider_availability_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_provider_availability_engagement
    ON public.provider_availability(engagement_id);


ALTER TABLE IF EXISTS public.provider_availability
    ADD CONSTRAINT provider_availability_provider_id_fkey FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provider_leaves
    ADD CONSTRAINT provider_leaves_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provider_leaves
    ADD CONSTRAINT provider_leaves_serviceproviderid_fkey FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provider_wallets
    ADD CONSTRAINT provider_wallets_serviceproviderid_fkey FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS provider_wallets_serviceproviderid_key
    ON public.provider_wallets(serviceproviderid);


ALTER TABLE IF EXISTS public.provider_ledger
    ADD CONSTRAINT provider_ledger_serviceproviderid_fkey FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_provider_ledger_serviceproviderid
    ON public.provider_ledger(serviceproviderid, created_at DESC);


ALTER TABLE IF EXISTS public.service_provider_feedback
    ADD CONSTRAINT fk6aa0beg2bdnivdc4l7f5jbm0x FOREIGN KEY (service_provider_id)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_feedback
    ADD CONSTRAINT fkpdcss1mkdj9weqhw901v21diy FOREIGN KEY (customer_id)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_leave
    ADD CONSTRAINT fkexqw5de8by0jq0x2lxuck7ytk FOREIGN KEY (backup_by_id)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_leave
    ADD CONSTRAINT fkklerl0uho2bw7kdlgnci73y0n FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_payment
    ADD CONSTRAINT fk2ss67l6nireofb5tga5qhn4vp FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_payment
    ADD CONSTRAINT fkmdrljqodeuvsjpo0ea0co6rot FOREIGN KEY (serviceproviderid)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_request_comments
    ADD CONSTRAINT fkhv0esa2q09eifkhqs5oq5279j FOREIGN KEY (requestid)
    REFERENCES public.serviceproviderrequest (requestid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_used_coupons
    ADD CONSTRAINT fkhtx313wjffxxmbyirjap91rrp FOREIGN KEY (service_provider_id)
    REFERENCES public.serviceprovider (serviceproviderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.service_provider_used_coupons
    ADD CONSTRAINT fklorel8mpnic2phicc9wod5x05 FOREIGN KEY (coupon_id)
    REFERENCES public.coupons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.serviceprovider
    ADD CONSTRAINT fk58tpyo1rr5i3r8cd0w35q55ca FOREIGN KEY (correspondence_address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk8c38m2dawmd5ks1m0v1mdvaqm
    ON public.serviceprovider(correspondence_address_id);


ALTER TABLE IF EXISTS public.serviceprovider
    ADD CONSTRAINT fkb85jfjip8phenf5g8xkjoqd1n FOREIGN KEY (permanent_address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukqt70pwr65bckmjmdftw66r40o
    ON public.serviceprovider(permanent_address_id);


ALTER TABLE IF EXISTS public.shortlisted_service_provider
    ADD CONSTRAINT fksbh28v3wreh5afqrigysdyvki FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transaction
    ADD CONSTRAINT wallet_transactions_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transaction
    ADD CONSTRAINT wallet_transactions_engagement_id_fkey FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transaction
    ADD CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.customer_wallets (wallet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_customerid_fkey1 FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_engagement_id_fkey1 FOREIGN KEY (engagement_id)
    REFERENCES public.engagements (engagement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallets
    ADD CONSTRAINT wallets_customerid_fkey1 FOREIGN KEY (customerid)
    REFERENCES public.customer (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS wallets_customerid_key1
    ON public.wallets(customerid);

ALTER TABLE IF EXISTS public.engagements
    ADD COLUMN IF NOT EXISTS address character varying(500) COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.engagements
    ADD COLUMN IF NOT EXISTS latitude double precision;

ALTER TABLE IF EXISTS public.engagements
    ADD COLUMN IF NOT EXISTS longitude double precision;

CREATE TABLE IF NOT EXISTS public.in_app_notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    recipient_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    recipient_id bigint NOT NULL,
    type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    title text NOT NULL,
    body text,
    engagement_id bigint,
    metadata jsonb,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT in_app_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT in_app_notifications_recipient_type_check
        CHECK (recipient_type = ANY (ARRAY['customer'::text, 'provider'::text]))
);

CREATE INDEX IF NOT EXISTS in_app_notifications_recipient_created
    ON public.in_app_notifications (recipient_type, recipient_id, created_at DESC);

CREATE INDEX IF NOT EXISTS in_app_notifications_unread
    ON public.in_app_notifications (recipient_type, recipient_id)
    WHERE (read_at IS NULL);

CREATE TABLE IF NOT EXISTS public.admin_alert_reads
(
    admin_user_id character varying(128) COLLATE pg_catalog."default" NOT NULL,
    alert_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    read_at timestamp(6) with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT admin_alert_reads_pkey PRIMARY KEY (admin_user_id, alert_key)
);

CREATE INDEX IF NOT EXISTS admin_alert_reads_admin_user_id_idx
    ON public.admin_alert_reads (admin_user_id, read_at DESC);

END;
