-- Idempotent: safe to run on any DB, including after full schema load.
-- Creates in-app notification storage if it was missing (e.g. old deploy, failed batch apply).

CREATE TABLE IF NOT EXISTS public.in_app_notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    recipient_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    recipient_id bigint NOT NULL,
    type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    title text NOT NULL,
    body text,
    engagement_id bigint,
    metadata jsonb,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT in_app_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT in_app_notifications_recipient_type_check
        CHECK (recipient_type = ANY (ARRAY['customer'::text, 'provider'::text]))
);

CREATE INDEX IF NOT EXISTS in_app_notifications_recipient_created
    ON public.in_app_notifications (recipient_type, recipient_id, created_at DESC);

CREATE INDEX IF NOT EXISTS in_app_notifications_unread
    ON public.in_app_notifications (recipient_type, recipient_id)
    WHERE (read_at IS NULL);
