name: Test SSH Connectivity

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options: [dev, qa, uat, prod]

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set EC2 Environment Config
        id: envcfg
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "Testing SSH for environment: $ENV"

          if [ "$ENV" = "dev" ]; then
            echo "host=${{ secrets.DEV_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.DEV_USER }}" >> $GITHUB_OUTPUT
            echo "key=${{ secrets.DEV_KEY }}" >> $GITHUB_OUTPUT

          elif [ "$ENV" = "qa" ]; then
            echo "host=${{ secrets.QA_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.QA_USER }}" >> $GITHUB_OUTPUT
            echo "key=${{ secrets.QA_KEY }}" >> $GITHUB_OUTPUT

          elif [ "$ENV" = "uat" ]; then
            echo "host=${{ secrets.UAT_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.UAT_USER }}" >> $GITHUB_OUTPUT
            echo "key=${{ secrets.UAT_KEY }}" >> $GITHUB_OUTPUT

          elif [ "$ENV" = "prod" ]; then
            echo "host=${{ secrets.PROD_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.PROD_USER }}" >> $GITHUB_OUTPUT
            echo "key=${{ secrets.PROD_KEY }}" >> $GITHUB_OUTPUT
          fi

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.envcfg.outputs.host }}
          username: ${{ steps.envcfg.outputs.user }}
          key: ${{ steps.envcfg.outputs.key }}
          script: |
            echo "SSH CONNECTION SUCCESSFUL!"
            echo "Hostname:" $(hostname)
            echo "Current user:" $(whoami)
            echo "Current directory:" $(pwd)
