name: Test SSH Connectivity

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options: [dev, qa, uat, prod]

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:

      - name: Set EC2 Environment Config
        id: envcfg
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "Selected environment: $ENV"

          if [ "$ENV" = "qa" ]; then
            echo "host=${{ secrets.QA_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.QA_USER }}" >> $GITHUB_OUTPUT

            # SAFELY write multiline SSH private key
            {
              echo "key<<EOF"
              echo "${{ secrets.QA_KEY }}"
              echo "EOF"
            } >> $GITHUB_OUTPUT
          fi

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.envcfg.outputs.host }}
          username: ${{ steps.envcfg.outputs.user }}
          key: ${{ steps.envcfg.outputs.key }}
          script: |
            echo "SSH CONNECTION SUCCESSFUL!"
            echo "Hostname:" $(hostname)
            echo "Current user:" $(whoami)
            echo "Current directory:" $(pwd)
